/* background_part1.js — CLEAN UTF-8, single registry (Places 140+) */
(function(g){
  const categories = [
    {
      name: 'Background Geometry / 背景ジオメトリ',
      items: [
        { id:'bg-dune-ridges', label:'砂丘の尾根 / dune ridges' },
        { id:'bg-wadi-canyon', label:'ワジ渓谷 / wadi canyon' },
        { id:'bg-rock-arches-desert', label:'砂漠の岩アーチ / desert rock arches' },
        { id:'bg-oasis-palm', label:'オアシスと椰子 / oasis with palms' }
      ]
    },
    {
      name: 'Composition / 構図・フレーミング',
      items: [
        { id:'low-angle-mirage', label:'ロウアングル・蜃気楼越し / low angle through mirage' },
        { id:'long-journey-lines', label:'遠近線で旅情 / long journey lines' },
        { id:'silhouette-dune-crest', label:'砂丘稜線のシルエット / silhouette on dune crest' }
      ]
    },
    {
      name: 'Places / 世界の場所',
      items: [
        { id:'bg-tokyo-shibuya', label:'渋谷スクランブル交差点 / Shibuya crossing' },
        { id:'bg-kyoto-gion', label:'京都 祇園 / Kyoto Gion' },
        { id:'bg-osaka-dotonbori', label:'大阪 道頓堀 / Osaka Dotonbori' },
        { id:'bg-sapporo-snow', label:'札幌 雪街 / Sapporo snow town' },
        { id:'bg-fuji-five-lakes', label:'富士五湖 / Fuji Five Lakes' },
        { id:'bg-nikko-shrine', label:'日光 東照宮 / Nikko shrine' },
        { id:'bg-nara-park', label:'奈良公園 / Nara park' },
        { id:'bg-okinawa-beach', label:'沖縄の浜 / Okinawa beach' },
        { id:'bg-himeji-castle', label:'姫路城 / Himeji castle' },
        { id:'bg-hiroshima-dome', label:'広島 原爆ドーム / Hiroshima A-Bomb Dome' },
        { id:'bg-seoul-myeongdong', label:'ソウル 明洞 / Seoul Myeongdong' },
        { id:'bg-busan-beach', label:'釜山 海雲台ビーチ / Busan Haeundae beach' },
        { id:'bg-beijing-hutong', label:'北京 胡同 / Beijing hutong' },
        { id:'bg-shanghai-bund', label:'上海 外灘 / Shanghai Bund' },
        { id:'bg-hongkong-skyline', label:'香港 スカイライン / Hong Kong skyline' },
        { id:'bg-taipei-101', label:'台北101 / Taipei 101' },
        { id:'bg-singapore-marina', label:'シンガポール マリーナ湾 / Singapore Marina Bay' },
        { id:'bg-bangkok-temple', label:'バンコク 寺院 / Bangkok temple' },
        { id:'bg-chiangmai-oldtown', label:'チェンマイ 旧市街 / Chiang Mai old town' },
        { id:'bg-kuala-lumpur-towers', label:'クアラルンプール ツインタワー / Kuala Lumpur twin towers' },
        { id:'bg-jakarta-oldtown', label:'ジャカルタ旧市街 / Jakarta old town' },
        { id:'bg-manila-intramuros', label:'マニラ イントラムロス / Manila Intramuros' },
        { id:'bg-delhi-red-fort', label:'デリー 赤い城 / Delhi Red Fort' },
        { id:'bg-mumbai-gateway', label:'ムンバイ インド門 / Mumbai Gateway of India' },
        { id:'bg-kathmandu-stupa', label:'カトマンズ ストゥーパ / Kathmandu stupa' },
        { id:'bg-dhaka-market', label:'ダッカ 市場 / Dhaka market' },
        { id:'bg-dubai-marina', label:'ドバイ マリーナ / Dubai Marina' },
        { id:'bg-abu-dhabi-mosque', label:'アブダビ グランドモスク / Abu Dhabi grand mosque' },
        { id:'bg-istanbul-bosphorus', label:'イスタンブール ボスポラス / Istanbul Bosphorus' },
        { id:'bg-cappadocia-balloon', label:'カッパドキア 熱気球 / Cappadocia balloons' },
        { id:'bg-cairo-pyramids', label:'カイロ ピラミッド / Cairo pyramids' },
        { id:'bg-marrakesh-medina', label:'マラケシュ メディナ / Marrakesh medina' },
        { id:'bg-casablanca-corniche', label:'カサブランカ 海岸通り / Casablanca corniche' },
        { id:'bg-lagos-skyline', label:'ラゴス スカイライン / Lagos skyline' },
        { id:'bg-nairobi-savanna', label:'ナイロビ サバンナ / Nairobi savanna' },
        { id:'bg-cape-town-table', label:'ケープタウン テーブルマウンテン / Cape Town Table Mountain' },
        { id:'bg-victoria-falls', label:'ビクトリアの滝 / Victoria Falls' },
        { id:'bg-rome-colosseum', label:'ローマ コロッセオ / Rome Colosseum' },
        { id:'bg-florence-duomo', label:'フィレンツェ ドゥオーモ / Florence Duomo' },
        { id:'bg-venice-canal', label:'ベネチア 運河 / Venice canals' },
        { id:'bg-milan-duomo-square', label:'ミラノ ドゥオーモ広場 / Milan Duomo square' },
        { id:'bg-paris-eiffel', label:'パリ エッフェル塔 / Paris Eiffel Tower' },
        { id:'bg-paris-montmartre', label:'パリ モンマルトル / Paris Montmartre' },
        { id:'bg-london-thames', label:'ロンドン テムズ川 / London Thames' },
        { id:'bg-london-camden', label:'ロンドン カムデン / London Camden' },
        { id:'bg-edinburgh-castle', label:'エディンバラ 城 / Edinburgh castle' },
        { id:'bg-dublin-templebar', label:'ダブリン テンプルバー / Dublin Temple Bar' },
        { id:'bg-berlin-brandenburg', label:'ベルリン ブランデンブルク門 / Berlin Brandenburg Gate' },
        { id:'bg-munich-marienplatz', label:'ミュンヘン マリエン広場 / Munich Marienplatz' },
        { id:'bg-hamburg-harbor', label:'ハンブルク 港 / Hamburg harbor' },
        { id:'bg-vienna-ringstrasse', label:'ウィーン リング通り / Vienna Ringstrasse' },
        { id:'bg-prague-charles', label:'プラハ カレル橋 / Prague Charles Bridge' },
        { id:'bg-budapest-parliament', label:'ブダペスト 国会議事堂 / Budapest parliament' },
        { id:'bg-athens-acropolis', label:'アテネ アクロポリス / Athens Acropolis' },
        { id:'bg-santorini-oia', label:'サントリーニ イア / Santorini Oia' },
        { id:'bg-madrid-plaza-mayor', label:'マドリード マヨール広場 / Madrid Plaza Mayor' },
        { id:'bg-barcelona-sagrada', label:'バルセロナ サグラダ / Barcelona Sagrada Familia' },
        { id:'bg-lisbon-alfama', label:'リスボン アルファマ / Lisbon Alfama' },
        { id:'bg-porto-ribeira', label:'ポルト リベイラ / Porto Ribeira' },
        { id:'bg-amsterdam-canal', label:'アムステルダム 運河 / Amsterdam canals' },
        { id:'bg-brussels-grandplace', label:'ブリュッセル グランプラス / Brussels Grand Place' },
        { id:'bg-copenhagen-nyhavn', label:'コペンハーゲン ニューハウン / Copenhagen Nyhavn' },
        { id:'bg-stockholm-gamlastan', label:'ストックホルム 旧市街 / Stockholm Gamla Stan' },
        { id:'bg-oslo-fjord', label:'オスロ フィヨルド / Oslo fjord' },
        { id:'bg-bergen-bryggen', label:'ベルゲン ブリッゲン / Bergen Bryggen' },
        { id:'bg-iceland-black-beach', label:'アイスランド 黒い砂浜 / Iceland black beach' },
        { id:'bg-reykjavik-harpa', label:'レイキャビク ハルパ / Reykjavik Harpa' },
        { id:'bg-moscow-red-square', label:'モスクワ 赤の広場 / Moscow Red Square' },
        { id:'bg-st-petersburg-neva', label:'サンクトペテルブルク ネヴァ川 / St.Petersburg Neva' },
        { id:'bg-krakow-oldtown', label:'クラクフ 旧市街 / Krakow old town' },
        { id:'bg-dubrovnik-walls', label:'ドゥブロブニク 城壁 / Dubrovnik walls' },
        { id:'bg-zurich-limmat', label:'チューリッヒ リマト川 / Zurich Limmat' },
        { id:'bg-geneva-lake', label:'ジュネーブ レマン湖 / Geneva lake' },
        { id:'bg-interlaken-alps', label:'インターラーケン アルプス / Interlaken Alps' },
        { id:'bg-paro-dzong', label:'パロ 寺院 / Paro dzong' },
        { id:'bg-lhasa-potala', label:'ラサ ポタラ宮 / Lhasa Potala palace' },
        { id:'bg-ulanbator-steppe', label:'ウランバートル 草原 / Ulaanbaatar steppe' },
        { id:'bg-anchorage-aurora', label:'アンカレッジ オーロラ / Anchorage aurora' },
        { id:'bg-newyork-manhattan', label:'ニューヨーク マンハッタン / New York Manhattan' },
        { id:'bg-newyork-centralpark', label:'ニューヨーク セントラルパーク / New York Central Park' },
        { id:'bg-boston-harbor', label:'ボストン 港 / Boston harbor' },
        { id:'bg-washington-mall', label:'ワシントンD.C. モール / Washington National Mall' },
        { id:'bg-miami-southbeach', label:'マイアミ サウスビーチ / Miami South Beach' },
        { id:'bg-chicago-riverwalk', label:'シカゴ リバーウォーク / Chicago riverwalk' },
        { id:'bg-seattle-pier', label:'シアトル ピア / Seattle pier' },
        { id:'bg-sanfrancisco-golden-gate', label:'サンフランシスコ 金門橋 / San Francisco Golden Gate' },
        { id:'bg-losangeles-santa-monica', label:'ロサンゼルス サンタモニカ / Los Angeles Santa Monica' },
        { id:'bg-lasvegas-strip', label:'ラスベガス ストリップ / Las Vegas strip' },
        { id:'bg-grand-canyon-rim', label:'グランドキャニオン 縁 / Grand Canyon rim' },
        { id:'bg-yosemite-valley', label:'ヨセミテ渓谷 / Yosemite valley' },
        { id:'bg-yellowstone-geyser', label:'イエローストーン 間欠泉 / Yellowstone geyser' },
        { id:'bg-zion-canyon', label:'ザイオン渓谷 / Zion canyon' },
        { id:'bg-mount-rainier-meadow', label:'レーニア山 高原 / Mount Rainier meadow' },
        { id:'bg-vancouver-stanley', label:'バンクーバー スタンレー公園 / Vancouver Stanley Park' },
        { id:'bg-toronto-cn', label:'トロント CNタワー / Toronto CN Tower' },
        { id:'bg-montreal-oldport', label:'モントリオール 旧港 / Montreal Old Port' },
        { id:'bg-quebec-oldtown', label:'ケベック旧市街 / Quebec old town' },
        { id:'bg-mexico-teotihuacan', label:'メキシコ テオティワカン / Teotihuacan' },
        { id:'bg-cusco-plaza', label:'クスコ 広場 / Cusco plaza' },
        { id:'bg-machu-picchu-view', label:'マチュピチュ 眺望 / Machu Picchu view' },
        { id:'bg-rio-corcovado', label:'リオ コルコバード / Rio Corcovado' },
        { id:'bg-rio-copacabana', label:'リオ コパカバーナ / Rio Copacabana' },
        { id:'bg-buenos-aires-la-boca', label:'ブエノスアイレス ラ・ボカ / Buenos Aires La Boca' },
        { id:'bg-santiago-andes', label:'サンティアゴ アンデス / Santiago Andes view' },
        { id:'bg-ushuaia-port', label:'ウシュアイア 港 / Ushuaia port' },
        { id:'bg-havana-oldtown', label:'ハバナ 旧市街 / Havana old town' },
        { id:'bg-caribbean-beach', label:'カリブ海 ビーチ / Caribbean beach' },
        { id:'bg-tahiti-lagoon', label:'タヒチ ラグーン / Tahiti lagoon' },
        { id:'bg-bora-bora-overwater', label:'ボラボラ 水上コテージ / Bora Bora overwater' },
        { id:'bg-sydney-opera', label:'シドニー オペラハウス / Sydney Opera House' },
        { id:'bg-melbourne-laneways', label:'メルボルン 路地 / Melbourne laneways' },
        { id:'bg-auckland-harbor', label:'オークランド 港 / Auckland harbor' },
        { id:'bg-queenstown-lake', label:'クイーンズタウン 湖畔 / Queenstown lakefront' },
        { id:'bg-uluru-ayers', label:'ウルル エアーズロック / Uluru (Ayers Rock)' },
        { id:'bg-rice-terraces', label:'棚田 / Rice terraces' },
        { id:'bg-bamboo-forest', label:'竹林 / Bamboo forest' },
        { id:'bg-cherry-blossom-park', label:'桜公園 / Cherry blossom park' },
        { id:'bg-maple-avenue', label:'紅葉並木 / Maple avenue' },
        { id:'bg-pine-forest', label:'松林 / Pine forest' },
        { id:'bg-rainforest-river', label:'熱帯雨林 川 / Rainforest river' },
        { id:'bg-mangrove-swamp', label:'マングローブ湿地 / Mangrove swamp' },
        { id:'bg-coral-reef', label:'珊瑚礁 / Coral reef' },
        { id:'bg-sandy-dunes', label:'砂丘 / Sandy dunes' },
        { id:'bg-salt-desert', label:'塩の砂漠 / Salt desert' },
        { id:'bg-canyon-overlook', label:'渓谷の見晴らし / Canyon overlook' },
        { id:'bg-mesa-plateau', label:'メサ台地 / Mesa plateau' },
        { id:'bg-volcanic-crater', label:'火山クレーター / Volcanic crater' },
        { id:'bg-geyser-field', label:'間欠泉地帯 / Geyser field' },
        { id:'bg-lava-field', label:'溶岩原 / Lava field' },
        { id:'bg-glacier-lake', label:'氷河湖 / Glacier lake' },
        { id:'bg-iceberg-bay', label:'氷山の湾 / Iceberg bay' },
        { id:'bg-fjord-cliff', label:'フィヨルド断崖 / Fjord cliff' },
        { id:'bg-steppe-grassland', label:'ステップ草原 / Steppe grassland' },
        { id:'bg-savanna-acacia', label:'サバンナ アカシア / Savanna acacia' },
        { id:'bg-baobab-avenue', label:'バオバブ並木 / Baobab avenue' },
        { id:'bg-oasis-dunes', label:'オアシス 砂丘 / Oasis among dunes' },
        { id:'bg-oasis-datepalm', label:'オアシス ナツメヤシ / Oasis date palms' },
        { id:'bg-coastal-cliffs', label:'海岸の断崖 / Coastal cliffs' },
        { id:'bg-tidepools', label:'潮だまり / Tide pools' },
        { id:'bg-kelp-forest', label:'昆布の森 / Kelp forest' },
        { id:'bg-lighthouse-coast', label:'灯台 海岸 / Lighthouse coast' },
        { id:'bg-harbor-piers', label:'港の桟橋 / Harbor piers' },
        { id:'bg-old-town-square', label:'旧市街広場 / Old town square' },
        { id:'bg-bazaar-market', label:'バザール市場 / Bazaar market' },
        { id:'bg-spaceport-runway', label:'スペースポート滑走路 / Spaceport runway' },
        { id:'bg-moon-base', label:'月面基地 / Moon base' },
        { id:'bg-mars-colony', label:'火星コロニー / Mars colony' }
      ]
    }
  ];

  const data = { categories, presets: [] };

  if (typeof g.__registerBackgroundPart === 'function') {
    g.__registerBackgroundPart('background_part1', data);
  } else {
    g.__parts = g.__parts || {};
    g.__parts.background = g.__parts.background || {};
    g.__parts.background['background_part1'] = data;
  }
})(window);
