// ============================================================
// ext_manifest.v2.js (Bundle-only + i18n locale packs)
// Generated: 2026-01-11
// ============================================================

window.EXT_MANIFEST = [
  "builder_core.v1.js",
  "i18n/i18n.core.js",
  "i18n/i18n.locale_registry_shim.js",
  "i18n/i18n.locale.ja.js",
  "i18n/i18n.locale.en.js",
  "builder_data.qp_base.js",
  "builder_data.qp_situations.js",
  "builder_data.quality_preset.js",
  "builder_data.preset_packs.js", 
  "builder_ui.section.quality_preset.bundle.js",
  "builder_ui.section.preset_packs.bundle.js",
  "builder_ui.section.style.bundle.js",
  "builder_ui.section.anatomy.bundle.js",
  "builder_ui.section.race.bundle.js",
  "builder_ui.section.bodytype.bundle.js",
  "builder_ui.section.traits.bundle.js",
  "builder_ui.section.hair.bundle.js",
  "builder_ui.section.skin_details.bundle.js",
  "builder_ui.section.attire.bundle.js",
  "builder_ui.section.accessories.bundle.js",
  "builder_ui.section.creatures.bundle.js",
  "builder_ui.section.texture.bundle.js",
  "builder_ui.section.expression.bundle.js",
  "builder_ui.section.pose.bundle.js",
  "builder_ui.section.narrative.bundle.js",
  "builder_ui.section.composition.bundle.js",
  "builder_ui.section.camera.bundle.js",
  "builder_ui.section.background.bundle.js",
  "builder_ui.section.lighting.bundle.js",
  "builder_ui.section.shadow.bundle.js",
  "builder_ui.section.atmosphere.bundle.js",
  "builder_ui.section.effect.bundle.js",
  "builder_ui.section.postprocessing.bundle.js",
  "builder_ui.section.filter.bundle.js",
  "builder_ui.section.presets.bundle.js",
  "builder_ui.preview_sync.v1.js",
  "builder_ui.visualsync.v4.js",
  "ext_autosave.js",
  "ext_detector.js",
  "ext_floating_panel.js",
  "ext_footer_search.js",
  "ext_history.js",
  "ext_simple_visualize.js",
  "ext_smart_edit.js",
  "ext_sync_check.js",
  "ext_i18n_section_labels.js",
  "ext_i18n_capture.js",
  "ext_i18n_tools.js",
  "ext_i18n_tooltip.js",
  "ext_i18n_yakuguid_panel.js",
];